Updates to basic-config to support MPV of Step Function Workflow
mintel/helm-charts pull request #166
Opened 2022-07-13 08:24 UTC by nabadger

- Allow `Service` and `ExternalSecrets` to support a `name` value (we need option to name these explicitly
- Fix podServiceSelectors again

2022-07-13 13:54 UTC, barrymars requested changes

2022-07-13 13:54 UTC, barrymars commented on charts/basic-config/values.yaml
> +  name: ""
i'd call this nameOverride, as a name would be created if it wasn't set

2022-07-13 13:54 UTC, barrymars commented on charts/basic-config/templates/service.yaml
> +  name: {{ default (include "mintel_common.fullname" $serviceData) .Values.service.name }}
might want to move this into a helped called something like `servicename`

and would need to be `{{ default (include "mintel_common.fullname" $serviceData) $serviceData.nameOverride }}`

will also need to check where else we are using the service name, eg: ingresses

2022-07-13 13:54 UTC, barrymars commented on charts/basic-config/templates/external-secrets.yaml
> +  name: {{ default (include "mintel_common.fullname" $secretData) .nameOverride }}
probably needs a dedicated helper too, as the value will be needed in other places, envFrom, stakater annotations, etc

2022-07-14 08:10 UTC, nabadger commented on charts/basic-config/templates/service.yaml
> +  name: {{ default (include "mintel_common.fullname" $serviceData) .Values.service.name }}
IK've added a helper `mintel_common.serviceName` and simplified it. I don't know why it was creating a custom `serviceData` dict (the standard-app-stack doesn't do that).

2022-07-14 08:55 UTC, nabadger commented on charts/basic-config/templates/external-secrets.yaml
> +  name: {{ default (include "mintel_common.fullname" $secretData) .nameOverride }}
I think this needs more thought as at the moment basic-config does not create any workloads (deployment etc) or Ingress. 

For now I've actually changed this to be consistant with the standard-app-stack.

That is - re-use the `extraSecrets` logic, added more tests, support `nameOverride`.

2022-07-14 10:55 UTC, barrymars approved these changes

2022-07-14 11:39 UTC, EmmanuelOgiji approved these changes

2022-07-14 11:39 UTC, merged